### ISSUE TITLE
Using meteor-iron-router-ga

### ISSUE THREAD

**Issue by hkirk** [Differential/meteor-blog#102]
Using this package
https://github.com/reywood/meteor-iron-router-ga
with your blog seems a bit problematic (or so it seems to me).

I can make this work if insert this
"window.ga && window.ga("send", "pageview", this.path);" in router.coffee in all onRun methods.

Any clues to use this package?
Using this package
https://github.com/reywood/meteor-iron-router-ga
with your blog seems a bit problematic (or so it seems to me).

I can make this work if insert this
"window.ga && window.ga("send", "pageview", this.path);" in router.coffee in all onRun methods.

Any clues to use this package?

**Comment by hkirk** [comment]
Still a problem - all routes in /blog/{title} are reported as / in GA :(

**Comment by uzumaxy** [comment]
The same problem.
