### ISSUE TITLE
ryw:blog not runnning properly w/ Meteor 0.9.3

### ISSUE THREAD

**Issue by harryhurry** [Differential/meteor-blog#109]
### Nice package, but:

Two errors are thrown when starting up Meteor after adding **ryw:blog**:
    `(STDERR) js-bson: Failed to load c++ bson extension, using pure JS version`
and 
    `Meteor._wrapAsync has been renamed to Meteor.wrapAsync`
as no other packges are added I guess  that these are caused by ryw: blog

To reproduce:
`meteor create blogtest`
`cd blogtest`
`meteor add ryw:blog`
`meteor' 

Any hint how to solve this?

**Comment by jirkadev** [comment]
Hi, seems to me, it is not fixed.

When using meteor@1.4.2.7 on Windows 8.1. I tried fresh install (besides having same error in my app)

 	$ meteor create testblog && cd test-blog && meteor
	$ meteor add iron:router
	$ meteor add ryw:blog

which resulted then in error (app works, but I would rather not have this error message in my log):

    W20170215-14:58:17.158(1)? (STDERR) js-bson: Failed to load c++ bson extension, using pure JS version
    I20170215-14:58:17.159(1)? { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

Error was also mentioned in 2016 by @LisaKG in the last comment https://github.com/meteor/meteor/issues/7477

**Comment by StickupArtist** [comment]
I assume this won't get fixed unless someone else picks up developing CollectionFS. _CollectionFS has been deprecated_. In order to get ryw:blog working, I had to go back to an earlier version of Meteor. I can't remember exactly what version that was, but I think it was the last of the 1.3 versions. Hope that helps.
