### ISSUE TITLE
Enhancement: Upload Feature Image for Posts

### ISSUE THREAD

**Issue by ericelias** [Differential/meteor-blog#124]
Allow upload of a feature image that could be called on the front page

**Comment by coopermaruyama** [comment]
I'm going to work on this soon, I think this is a fundamental feature that is missing from metor-blog. If everyone can give me feedback on my plan so far, that  would be great:

- the medium editor library we are using does not have a feature for featured images. However, the editor on medium.com has a nice one, it's just a icon you can click to the left of the title. I'm planning on copying this UI and extending `medium-editor.js`.

- There are different layouts you can choose for the featured image, one of which makes the image a parallax background and changes the font color to a color that contrasts against it (so if you upload a black image the text turns white). I probably won't implement this auto color change feature.

 - I'm planning on using the featured image of each post as thumbnails on the front page and category pages of the blog. The featured image URL will be stored in it's own column.

- I'm not sure whether the HTML for the featured image should be saved in the same field as the post content in the database, or if it should be generated and appended when rendering or editing. I feel like medium editor will mess it up when serializing the post content or medium-editor-insert might mess it up, too. Thoughts?

I think that covers the important stuff, let me know your thoughts.

**Comment by hellogerard** [comment]
@coopermaruyama,

Cool!

1. If you modify `medium-editor.js`, perhaps you should make PRs to the original repo. Then, blog can just upgrade it. In general, I like `medium-editor.js` overall, but the `medium-editor-insert-plugin` needs lots of work.I think it contributes to most of the editor problems. Wish there was a way to get nice image uploads without `medium-editor-insert-plugin`.

1. Start small, I say.

1. Sounds good,

1. I definitely think it should be stored in its own field, and not along with the post content. As for generating, on one hand, I usually don't store what I can re-generate, but it also saves a bit of render time if you store it. In this case, I'd say store the whole generated HTML. That's what we're doing with the blog post excerpt.

**Comment by semikolon** [comment]
+1

**Comment by insaneinc01** [comment]
+1

**Comment by apaleja** [comment]
+1

**Comment by coopermaruyama** [comment]
Alright here's my first PR for this: #161 

Feedback appreciated, expect some bugginess, let me know if you find any

**Comment by hellogerard** [comment]
Closed by #161. Yay!
