### ISSUE TITLE
Draft posts are publicly available

### ISSUE THREAD

**Issue by idmontie** [Differential/meteor-blog#128]
Posts that are still in draft are available by direct link to users who are not logged on.

To replicate, create a blog post, but do not publish it.  Use an incognito window and go to `/blob/post-slug`.  You will be able to get to the post without any issues.

Is this by design?  I would think that draft posts would be unavailable.  Maybe there should be Publish, Private, and Draft options where Draft is only viewable by blog admins, Private is available via direct link, and Published is actually listed in the blog?

**Comment by coopermaruyama** [comment]
Solved in #163
