### ISSUE TITLE
Have Publish, Private, and Draft post modes

### ISSUE THREAD

**Issue by hellogerard** [Differential/meteor-blog#129]
I would think that draft posts would be unavailable. Maybe there should be Publish, Private, and Draft options where Draft is only viewable by blog admins, Private is available via direct link, and Published is actually listed in the blog?

See #128.

**Comment by sasikanth513** [comment]
+1 for this

**Comment by semikolon** [comment]
+1

**Comment by andrerfneves** [comment]
Great idea. +1

**Comment by hellogerard** [comment]
Partially solved by #163. You can now globally set draft posts to be public or private. But ideally, you could set the mode of an individual post.
