### ISSUE TITLE
The "fb-root" div has not been created, auto-creating

### ISSUE THREAD

**Issue by nikhildaga** [Differential/meteor-blog#139]
I am getting this warning after installing meteor-blog. The sad part is that this warning is on all the pages on the site and not just blog posts. How can this be fixed?
Thanks. :)

**Comment by hellogerard** [comment]
This is an error you'll see on many, many websites that load the Facebook JS library. It's only a warning and has never caused me any harm.

While the absence of the div does not cause harm, my fear is that if your app already includes the div, and then the blog package includes the div, then there will be two divs with the same ID. So I've left it out.

**Comment by nikhildaga** [comment]
Thanks @hellogerard :) 
I was wondering why does it appear on every page? Is the facebook JS library loaded on pages other than blog pages too? 
Is there a way to limit the addition of fb js lib to only blog pages?

Thank you!

**Comment by craigs100** [comment]
I've done this to get over it:-

	// FB Like/Share buttons
	if ($('#fb-root').length > 0) {
		(function (d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&appId=12345678910111&version=v2.0";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
	}

**Comment by Grabber** [comment]
The "fb-root" div has not been created, auto-creating

Same here.

**Comment by MitchFortier** [comment]
I'm seeing the same issue.

@craigs100 Do you mind if I ask where you placed that bit of code. I've tried inserting it into multiple places but I can't seem to solve the issue.

**Comment by thiyagarajan** [comment]
I am also facing same issue. 

"The "fb-root" div has not been created, auto-creating"
