### ISSUE TITLE
Auto-save/Field validation notifications constantly refreshing

### ISSUE THREAD

**Issue by nicholasalanbrown** [Differential/meteor-blog#148]
Hello:

Upon installing the package and editing a new post, I'm immediately presented with the "blog title is a required field" warning. Upon filling in a title, the "saved" notification appears again and again even when the page is idle and no text is being entered.

Great package, though.

Nick

**Comment by coopermaruyama** [comment]
Fixed in #150

**Comment by nicholasalanbrown** [comment]
Resolved. Thanks!
