### ISSUE TITLE
blogAuthor can't view own posts

### ISSUE THREAD

**Issue by nicholasalanbrown** [Differential/meteor-blog#151]
Hello again:

Loving this package. I've forked it in order to customize the views a bit to my own needs, but no complaints thus far.

I'm having one weird issue - after adding meteor-roles and setting up a server-side method that automatically assigns new users to "blogAuthor," things seem to be working fine when creating a post. I can click and create, then save a post, but when I try and view "My Posts" the dashboard flashes for a split second and then just renders the blog feed. I've looked at the code and it seems to be doing the right checks - is this because there's a filter at the top of the dashboard for admins to toggle between all posts/their own posts? 

Would love to be able to fix this since my use case is a crowd-edited platform and this is a crucial feature. It'll also be good if there was no lag between the validation of the user role and redirecting to the blog feed.

**Comment by hellogerard** [comment]
I can reproduce this, so we'll get it fixed here shortly.

**Comment by nicholasalanbrown** [comment]
Great! This solves the problem of allowing blogAuthor to see the dashboard of posts, but now all authors can see all posts. Isn't the intended functionality that as an author I'd only see my own posts? That is, there's no need for the "All Posts" vs "My Posts" filter on the dashboard for authors? Also, posts that blogAuthor creates shows up in the blog feed whether or not it was created by the logged in user, and whether or not it's been published...

Let me know if you can reproduce...

**Comment by hellogerard** [comment]
1. I believe my original intent was that all authors could see all posts, yes, whether in the admin or in the public blog feed. They just can't modify all posts. This wasn't intended to be a multi-tenant blog (like it sounds like you want), but rather like a shared blog among a single company or group. Think of it as single Wordpress instance – it sounds like you want something like Wordpress Network.

That said, it probably wouldn't be difficult to do so. If you want, create another issue with your exact  requirements.

1. The filter is just for convenience.

1. Unpublished blogs should not show up in the public blog feed (though you can still load it directly). That would be a bug.

**Comment by nicholasalanbrown** [comment]
What a thorough explanation. I looked again at the package documentation and it's clear I read into the "authorRole - Can create, and modify or delete only my own posts." and made the assumption it meant I would see only my own work. Perhaps what we're talking about it is a second role, i.e. "blogEditor" which has the current functionality (that is you could look at other work in progress, perhaps with the ability to make the call on authors' publications, but not edit), and one like I'm describing, a new "blogAuthor" that could only manage and see its own posts.

Thanks for the offer! I'll log a separate ticket for the functionality I'm looking for. I think it would actually be a great addition, as Meteor's reactivity and speed makes it very well suited for a larger crowd-contributed content community. 

Either way, I'm definitely seeing the bug I described where unpublished stories by blogAuthors show up in the blog feed. 

You guys are super responsive. Great community on this package!
