### ISSUE TITLE
Feature Request: Sharing out of the box

### ISSUE THREAD

**Issue by yejodido** [Differential/meteor-blog#153]
Would love to see a default sharing utility for the standard social networks.

**Comment by hellogerard** [comment]
Hi Joey,

By default, the 'shareit' package is included and enabled on the default
templates.

Does this address your issue?

**Comment by yejodido** [comment]
Ah, looks to be an adblockplus issue. I see the tabs after disabling.

**Comment by queso** [comment]
I am going to release an updated version of shareIt soon and it will add pinterest support and g+ support.

**Comment by queso** [comment]
@yejodido usually adblockplus picks up on things because of class naming. Which site were you seeing blocked buttons on?

**Comment by yejodido** [comment]
@queso After reading any blog post, just after the post and below the dash, inside the footer element. I'm almost certain it's a font-awesome issue, but it's curious that it disables the entire div and not just the <i>.
