### ISSUE TITLE
Changing the whole site name to "Blog"

### ISSUE THREAD

**Issue by javierocanas** [Differential/meteor-blog#158]
Firstly thanks for this awesome package! :heart_eyes: 

When i open the blog the `<title>` of my site change to "Blog"no matter if i go to other routes later, thanks :+1: :+1:

**Comment by coopermaruyama** [comment]
You need to set it back using `document.title = 'some title'`. If using iron router you should be able to do it in your after hook like `this.route('someRoute', {path: '/some-path', after: function() { document.title = 'Some path'; }})`

**Comment by javierocanas** [comment]
Hey cool man that helps, thank you bud :+1:  @coopermaruyama

**Comment by hellogerard** [comment]
@javierocanas Yes, iron-router (and meteor in general as a single-page-app) requires special handling of the page title. Here's a recent thread on the matter:

https://groups.google.com/forum/#!topic/meteor-talk/earnDjNSHGw

**Comment by javierocanas** [comment]
@hellogerard  Thanks buddy i learned something new :+1:

**Comment by futurechris** [comment]
@hellogerard While this can certainly be fixed on a case-by-case basis as described above, it seems pretty easy to let users prevent this override behavior, if they want to.

I've fixed this for my own use by adding a `Blog.settings.retainPageTitle` option that skips the two overwriting `document.title` assignments in the current code.

Would you be interested in a (tiny) pull request with this change?
