### ISSUE TITLE
Error starting site up in production with Meteor-Blog

### ISSUE THREAD

**Issue by hkirk** [Differential/meteor-blog#159]
:~/html/new/bundle$ node main.js
/home/www/html/new/bundle/programs/server/node_modules/fibers/future.js:173
						throw(ex);
						      ^
TypeError: Cannot call method 'split' of undefined
    at Function.Post.Post.excerpt (packages/ryw:blog/collections/post.coffee:48:22)
    at __coffeescriptShare (packages/ryw:blog/server/boot.coffee:39:34)
    at /home/www/html/new/bundle/programs/server/boot.js:212:5

Any idea where or why I'm getting this error. The code in post.coffee:48, don't give me any ideas.

Hope you can help.

**Comment by hkirk** [comment]
Had posts where body didn't exists - don't if this is an error. But maybe check for body before assuming it's there.

**Comment by coopermaruyama** [comment]
Fixed in #162
