### ISSUE TITLE
Update medium-insert-plugin to v1.0+

### ISSUE THREAD

**Issue by coopermaruyama** [Differential/meteor-blog#164]
https://github.com/orthes/medium-editor-insert-plugin

We're using v0.3.2 and the latest release is 1.0.3, and looking at the code it's completely different but fixes tons of issues. Opening this issue as a reminder to update to the latest version, as it will probably fix/improve tons of stuff.

**Comment by hellogerard** [comment]
Looks like the new version has a [lot more dependencies](https://github.com/orthes/medium-editor-insert-plugin/wiki/v1.0-Upgrading-from-v0.3). Will take time to sort out. 

Do you think it fixes the same issues fixed in 856d661c019848e97465814767b7c860162f1208?

**Comment by coopermaruyama** [comment]
I just did a quick test on their demo, and the duplicate event binding issues are definitely solved. Also, it will integrate into meteor-blog much more cleanly if done right since the modularity is improved, therefore we can get a lot more functionality out of it. It will probably take some work, but in the long run I think it'll make things much easier.

**Comment by hellogerard** [comment]
Started looking at upgrading `medium-editor` and `medium-editor-insert-plugin`. This is the main blocker to a new package release. The other issues and PRs aren't a lot of work. Hopefully get a new release out soon!

**Comment by hellogerard** [comment]
Have upgraded medium editor and insert plugin mostly working in https://github.com/Differential/meteor-blog/commits/update-medium-editor

**Comment by hellogerard** [comment]
Closed in 4a116d80d71344e915835e7ec62d0fbde9be31cc
