### ISSUE TITLE
Issues getting started, when I add the package, the routes are empty

### ISSUE THREAD

**Issue by micahblu** [Differential/meteor-blog#165]
First off I absolutely love this! Big fan of Medium and this does them proud :) I'm a bit new to Meteor and perhaps I'm doing something wrong. I have done the following, however my /blog and /admin/blog routes are the default Welcome to Meteor views.

```bash
$ meteor create my-blog
$ cd my-blog
$ meteor add ryw:blog
```

At that points everything seemed to be ok, I got a message saying I should get rid of auto publish, which I did. However from there as I mentioned visiting the blog routes just showed the default Meteor Welcome views. Sure I'm missing something. You're help is appreciated :)

**Comment by rgoomar** [comment]
I believe you have to be logged in to create blog posts and it won't show anything really until you have done so. 
So, you can use the basic `accounts-ui` package along with `accounts-password` and login and try to create a post and see if that works.

**Comment by micahblu** [comment]
Thanks that worked
