### ISSUE TITLE
Boilerplate and Blog Mashup - SEO issues

### ISSUE THREAD

**Issue by jmlivingston** [Differential/meteor-blog#166]
My apologies in advance as this is more of a question than an issue per se, but are the differential-blog and differential-boilerplate meant to play well together. The boilerplate appears to use spiderable and blaze-meta, while the blog uses ms-seo for SEO. I found a way to use them together, but find the OpenGraph meta tags don't get inserted immediately for the blog. This isn't a problem with Facebook or Google+, but LinkedIn is way more picky and doesn't pick up the OG tags. That said, I am not seeing this problem on the Differential blog. I'm pretty new to Meteor, so appreciate any tips. Thanks

**Comment by hellogerard** [comment]
I wouldn't say that the boilerplate and this package are meant to work together. So what you are seeing is entirely possible. The Differential blog is now on Ghost, for various reasons, so it's not a good example. Need to take that out of the README :-)

**Comment by jmlivingston** [comment]
@hellogerard - Thanks for the tip about Ghost, I will definitely check it out. I've been toying with Jekyll as well.
