### ISSUE TITLE
Use custom layout

### ISSUE THREAD

**Issue by theduke** [Differential/meteor-blog#167]
Right now, the default layout configured for iron:router is used.

How would I go about changing the layout for the blog pages?

**Comment by hellogerard** [comment]
If I understand your question, you want to use one layout for your site, and a different one for the blog?  I could see a configuration setting for layout that the routes in the blog packages would look for and use if present. Would make a good enhancement.

**Comment by tikitariki** [comment]
Yes. I was looking for a way to change a iron-router route, but I don't you can modify a route after they are created. I am asking around. Is this high on your list? I may want to give this a shot

**Comment by aramix** [comment]
what about this?

**Comment by theduke** [comment]
I fixed this with a hack by changing the layout in a custom before action Iroun Router callback.
Just register a before hook restricted to the name of the blog routes.

**Comment by aramix** [comment]
@theduke thanks a lot for a great workaround :+1:
