### ISSUE TITLE
static output for githubpages

### ISSUE THREAD

**Issue by omidfi** [Differential/meteor-blog#168]
Hi,
How hard would it be to make this blog create static html output, so that It can be used for github pages? Like ghost or jekyll?

**Comment by hellogerard** [comment]
@omidfi This would be no harder, and no easier, than creating static HTML output for Meteor in general. Meteor, like other SPA-type frameworks, do most of its rendering on the client. Generating static HTML such that it plays nicely with client-side HTML is actually somewhat difficult.

Meteor currently relies on the [spiderable](https://github.com/meteor/meteor/tree/devel/packages/spiderable) package for static output. You could wire something up with it to automatically generate new static pages from this package's output, but in my opinion it would not be trivial.
