### ISSUE TITLE
Constraint vsivsi:file-collection@0.3.3 is not satisfied

### ISSUE THREAD

**Issue by ganySA** [Differential/meteor-blog#171]
I am using meteor 1.xx and had to install using @0.6.0 otherwise i get the nasty 
ryw:blog: INCOMPATIBLE WITH METEOR 0.9.0 OR LATER message.

However now when installing i get the following error:
error: Conflict: Constraint vsivsi:file-collection@0.3.3 is not satisfied by vsivsi:file-collection 1.0.1.
Constraints on package "vsivsi:file-collection":
* vsivsi:file-collection@=1.0.1 <- top level
* vsivsi:file-collection@0.3.3 <- ryw:blog 0.6.3

When i install using just 
meteor add ryw:blog

It installs without problems but doesnt work in meteor 1.0

Update: I managed to get this to work when i custom downloaded the package and drop it in the package directory and then tweak the package file up to 1.0.1.......

**Comment by tenshiemi** [comment]
Just to add on to this, I did the same thing (manually updated the dependency) and it seems to work fine with the new versions of file-collection. I was able to add/remove images on my blog posts.

**Comment by ganySA** [comment]
To give a bit more context (for those who want to use meteor windows) - i was actually attempting to get blog working with windows meteor build (the pre-release). 

File-collection wouldnt install at all - I posted an issue on file-collection regarding windows - the response was a recompile was needed.... hence i dropped in the latest version to compile and then had the address the version issue above.

**Comment by hellogerard** [comment]
Updated in #182!

This should make it in next release, but I hesitate slightly because I believe that 1.0.1 has an issue if you want to deploy this package to Modulus.

[1] https://github.com/vsivsi/meteor-file-collection/issues/52
[2] https://github.com/onmodulus/demeteorizer/issues/125
