### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by trusktr** [Differential/meteor-blog#176]
in the wild?

**Comment by hellogerard** [comment]
https://getliquid.io/blog (older version)
https://rishigoomar.com/blog/simple-ci-testing-setup-with-travis-gulp-mocha

Others can submit their examples. 

We used to run this package on http://differential.com, but for various reasons, mainly around better user accounts, replaced it with Ghost.

**Comment by trusktr** [comment]
Cool, thanks! What was the advantage of Ghost's accounts vs Meteor's accounts?

**Comment by hellogerard** [comment]
Another example: http://www.meteorsnippets.com/blog
