### ISSUE TITLE
Sharing with ShareIt

### ISSUE THREAD

**Issue by hkirk** [Differential/meteor-blog#177]
Sharing a blog post with ShareIt on facebook just shows up as a "Loading..." anything that can be done to share the title and possible image if exists?

![screen shot 2015-04-01 at 9 37 13 am](https://cloud.githubusercontent.com/assets/201625/6936458/b8f64572-d852-11e4-8737-f5ccad2aa37f.png)

**Comment by hellogerard** [comment]
Sounds like more an issue with ShareIt than meteor-blog. And in either case, might just be a spiderable issue with your setup. Do you know if you get the issue consistently? Does ShareIt work with a different app?

**Comment by hellogerard** [comment]
Closing...
