### ISSUE TITLE
Explanation of what `Meteor.user()` means

### ISSUE THREAD

**Issue by ajcrites** [Differential/meteor-blog#178]
It seems that this add-on is made for users who are already somewhat familiar with Meteor and would know what

> `/admin/blog` requires that `Meteor.user()` return a user.

actually means.  I can't really find information about this in the meteor docs per se other than setting up a login page and things like that.  I think that it would be useful for this project to include instructions required to at least get to the point of starting (i.e. having a user you can administrate with) or include an example that does so.

**Comment by praneybehl** [comment]
@ajcrites 
/admin/blog requires that Meteor.user() return a user.
It means that a user should be logged-in in order to be able to access the route /admin/blog

**Comment by kahmali** [comment]
Here is a great resource from the Meteor team on logging a user in (which gives you access to that user as `Meteor.user()` when done from the client): https://www.meteor.com/try/9

I think it would be unfair (and slow progress) to require every package developer to explain things like this in their docs that are very well documented elsewhere. Maybe they can drop a link in there, but there are enough resources out there for something like this that doing anything more would probably be a waste of their time. Just my two cents. Hope the tutorial clears everything up!

**Comment by 3210jr** [comment]
I would suggest in addition to @kahmali that you go on and read the documentation over at http://docs.meteor.com/#/full/meteor_user . Also go ahead and familiarize yourself with that page it has saved my butt too many times!

**Comment by hellogerard** [comment]
Thanks guys!
