### ISSUE TITLE
Adding a search feature

### ISSUE THREAD

**Issue by gregorygilles** [Differential/meteor-blog#179]
How would one start to implement a search feature into their meteor-blog? I was thinking something that could display the posts that contain a certain keyword in the title, tag, description, or "body" of the post. By "body", I mean the body of the post displayed using {{{html}}} in show.html. 

Basically, I am asking how to access the text in {{{html}}} in javascript code for each post. However, if there is an easier way to add a search feature, that would be great to hear about too.

**Comment by hellogerard** [comment]
I consider this to be outside the scope of this package, but it is a nice idea. Filing this under enhancements.

There are lots of ways to implement general search in Meteor. This [blog post](https://meteorhacks.com/implementing-an-instant-search-solution-with-meteor.html) describes one such way. Take a look.

Also, check out http://forums.meteor.com and search for relevant topics.

**Comment by hellogerard** [comment]
Another great blog post on implementing search, this time relying on Mongo's own full-text search: http://www.okgrow.com/posts/2015/04/27/guide-to-full-text-search-in-meteor/

**Comment by hellogerard** [comment]
Going to close this, as there's plenty of other enhancements to get to :-P
