### ISSUE TITLE
Blog.differential package compatible for Windows?

### ISSUE THREAD

**Issue by majka-meteor** [Differential/meteor-blog#180]
Hi, 

Do you plan to do this package compatible for Windows 8.1 ?

Thank a lot,

Have a nice day,

Majka

**Comment by hellogerard** [comment]
Majka,

Any specific issues you're running into? Chances are this package should work fine on Windows out-of-the-box if you run it under Meteor 1.1+

**Comment by Nathan-022** [comment]
Same thing is happening to me on windows 7...

I get 'while checking for vsivsi:file-collection@0.3.3: error: no compatible binary build for this package'

when I try to meteor add ryw:blog. So the package won't install at all or work

**Comment by hellogerard** [comment]
Ah, should be a matter of upgrading file-collection to its latest ([see changelog](https://github.com/vsivsi/meteor-file-collection/blob/master/HISTORY.md)). I will do so in this next relase.
