### ISSUE TITLE
Error: method 'isBlogAuthorized' Error: Did not check() all arguments during call to 'isBlogAuthorized'

### ISSUE THREAD

**Issue by praneybehl** [Differential/meteor-blog#181]
When I try to navigate to add blog post it bounces off and on the server console I get the below error.

Anyone come across such error? Know how to fix/bypass it?

Thanks,
Praney

Here is the error code:
I20150411-21:40:57.265(10)? Exception while invoking method 'isBlogAuthorized' Error: Did not check() all arguments during call to 'isBlogAuthorized'
I20150411-21:40:57.266(10)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150411-21:40:57.266(10)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150411-21:40:57.266(10)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
I20150411-21:40:57.266(10)?     at packages/ddp/livedata_server.js:648:1
I20150411-21:40:57.266(10)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150411-21:40:57.266(10)?     at packages/ddp/livedata_server.js:647:1
I20150411-21:40:57.267(10)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150411-21:40:57.267(10)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150411-21:40:57.267(10)?     at packages/ddp/livedata_server.js:546:1

**Comment by coopermaruyama** [comment]
If you leave both `Blog.settings.authorRole` and `Blog.settings.adminRole` empty then it will let anyone into the admin area and at least you can try to debug it from there. I'm not familiar with that error code unfortunately so that's all I can tell ya.

Also I'm pretty sure that check only runs if `authorRole` is set so if the above works then try setting `Blog.settings.adminRole` but keep `Blog.settings.authorRole` undefined until you figure it out.

**Comment by 1thrasher** [comment]
This package doesn't pass the requirements of the [`audit-argument-checks`](http://docs.meteor.com/#/full/auditargumentchecks) package. I'll try to investigate precisely why that is, but for now, I suspect @praneybehl you can remove that package and it will work fine.

**Comment by praneybehl** [comment]
Thanks, Yes I've dropped it.
