### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by stewiegaribaldi** [Differential/meteor-blog#183]
I experienced this on running meteor:
=> Exited with code: 8
W20150526-21:21:22.156(10)? (STDERR)          
W20150526-21:21:22.157(10)? (STDERR) /.meteor/packages/vsivsi_file-collection/.0.3.5.1xtixlj++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:246
W20150526-21:21:22.157(10)? (STDERR)         throw message;      
W20150526-21:21:22.157(10)? (STDERR)               ^
W20150526-21:21:22.161(10)? (STDERR) TypeError: Cannot read property 'length' of undefined
W20150526-21:21:22.161(10)? (STDERR)     at processResults (/.meteor/packages/vsivsi_file-collection/.0.3.5.1xtixlj++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1607:31)
W20150526-21:21:22.161(10)? (STDERR)     at .meteor/packages/vsivsi_file-collection/.0.3.5.1xtixlj++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1645:20
W20150526-21:21:22.161(10)? (STDERR)     at /.meteor/packages/vsivsi_file-collection/.0.3.5.1xtixlj++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1183:7
W20150526-21:21:22.161(10)? (STDERR)     at .meteor/packages/vsivsi_file-collection/.0.3.5.1xtixlj++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1916:9
W20150526-21:21:22.161(10)? (STDERR)     at Server.Base._callHandler (/.meteor/packages/vsivsi_file-collection/.0.3.5.1xtixlj++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
W20150526-21:21:22.161(10)? (STDERR)     at .meteor/packages/vsivsi_file-collection/.0.3.5.1xtixlj++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
W20150526-21:21:22.161(10)? (STDERR)     at [object Object].MongoReply.parseBody (//.meteor/packages/vsivsi_file-collection/.0.3.5.1xtixlj++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
W20150526-21:21:22.162(10)? (STDERR)     at [object Object].<anonymous> (/.meteor/packages/vsivsi_file-collection/.0.3.5.1xtixlj++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
W20150526-21:21:22.162(10)? (STDERR)     at [object Object].emit (events.js:95:17)
W20150526-21:21:22.162(10)? (STDERR)     at [object Object].<anonymous> (.meteor/packages/vsivsi_file-collection/.0.3.5.1xtixlj++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)

If i do 'meteor remove ryw:blog, running meteor works.
any clue?

**Comment by stewiegaribaldi** [comment]
After installing and run meteor, it works ok. But once i break the running application and re-run it by typing meteor, then error occurs ...

**Comment by stewiegaribaldi** [comment]
My quick fix is modifying npm/node_modules/mongodb/lib/mongodb/db.js line 1611 processResult = function ... and add if (indexes == null) return info;

**Comment by hellogerard** [comment]
Can you try again with the latest release? I've upgraded `file-collection`.

**Comment by stewiegaribaldi** [comment]
Sorry, been so busy, i'll try to do it asap ... I just stuck on another problem.

**Comment by kafechew** [comment]
Hi, mine is not working...

> 	-----------------------------------STDOUT-----------------------------------
	=> re-installing binary npm module 'kerberos' of package 'vsivsi_file-collection'
	make: Entering directory `/opt/geosenti/tmp/bundle/programs/server/npm/vsivsi_file-collection/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
	  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
	make: Leaving directory `/opt/geosenti/tmp/bundle/programs/server/npm/vsivsi_file-collection/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
	----------------------------------------------------------------------------

Temporary, have to remove the ryw:blog package
