### ISSUE TITLE
Access posts from non /blog page

### ISSUE THREAD

**Issue by stewiegaribaldi** [Differential/meteor-blog#185]
I wonder if I can access the posts in my own custom template that's not in /blog ?
I have 2 routes i.e. web-page and mobile ...

**Comment by hellogerard** [comment]
The blog posts are a normal Meteor publication like any other. So you should have access to them if you subscribe on the route or template or where ever. 

If the publication in the package isn't parameterized right, then you could also create your own publication and subscription. Data in the database is for everybody!

HTH.

**Comment by stewiegaribaldi** [comment]
Thank you for your response hellogerard, but i have tried just subscribing to posts / blog_posts and nothing is shown; I have also tried to create publication but when i created the collection it errors: Error: A method named '/blog_posts/insert' is already defined. I'm still new in Meteor, apologise in advance.

**Comment by hellogerard** [comment]
The publications are all defined in: https://github.com/Differential/meteor-blog/blob/master/server/publications.coffee To access on the client, you have have an active subscription to the publication of the same name on any given page.

**Comment by stewiegaribaldi** [comment]
Thank you so much for the clue, Hellogerard ... I thought we cannot access other package collection. My mistake was I try to do Posts.find .. because in my head all collection has 's', i realise it is just Post.find.
And coffee-script is not my cup of tea =). Thank you, great package!!!

**Comment by shyal** [comment]
Could we have an example of this? How to access Collections from the package without the collection object?

**Comment by jupiterkenji** [comment]
Shyal, i don't understand what do you mean by 'without the collection object' .... as hellogerard suggested, we can access other package collection just like your own collection and I noted that I confuse myself by having the 's' letter.

**Comment by shyal** [comment]
Could you provide a code example? I can't create a collection object as I get an error saying the insert method for that collection already exists.

**Comment by jupiterkenji** [comment]
just google meteor collection example i.e. [meteor collection guide](http://guide.meteor.com/collections.html). But I think your issue is that you have same name as 'Post' i.e. Post = new Mongo.Collection('yourPostCollection'); To prove my theory, just create new meteor project  and try to access the blog Post ...

**Comment by shyal** [comment]
Could you provide a code example?


```
@P = new Meteor.Collection("blog_posts")

freeForAll =
  insert: (userId, doc) ->
    true
  update: (userId, doc, fields, modifier) ->
    true
  remove: (userId, doc) ->
    true

P.allow(freeForAll)
```

`collection.js:215Uncaught Error: There is already a collection named 'blog_posts'Mongo.Collection @ collection.js:215_0x19bfx8.(anonymous function) @ collections.js:1ns.Collection @ collection-extensions.js:83(anonymous function) @ posts.coffee:1(anonymous function) @ posts.coffee:1
`

Could you provide a code example?

**Comment by jupiterkenji** [comment]
why you define blog_posts? it has been defined in meteor-blog collections/post.coffee ; that is why you have the duplicate. Just use it right away ... i know you keep asking for example but it is just  misunderstanding ... i don't have example besides using the posts right away in my code i.e. Posts.find({...}) ...

**Comment by stewiegaribaldi** [comment]
just stumbled on my old code. you can use the post directly like so without re-defining it again. Let me know if it helps.

```
Template.mobilepost.helpers({
    posts: function () {
		return Blog.Post.find({});
    },
....
```
