### ISSUE TITLE
Remove fontawesome injection

### ISSUE THREAD

**Issue by dubvfan87** [Differential/meteor-blog#189]
Wouldn't it be better to just use https://atmospherejs.com/fortawesome/fontawesome as a dependency instead of injecting font awesome in the DOM via Meteor.startup?

The old version of fa 4.0.3 is breaking my new icons from 4.3.0

**Comment by hellogerard** [comment]
I believe the original reason was just to keep the number of dependencies down. The blog package pulls in a ton of packages already. What do you think if we just bump the CDN version to 4.3.0?

**Comment by dubvfan87** [comment]
Ah, I understand, but a lot of other packages already depend on that fontawesome:fontawesome package anyway, so if meteor-blog injects it's own version than we end up with 2 stylesheets in the head.

I'm integrating the blog into a rather large website, so I may not be the normal use case. I ended up just forking and removing the line, so I'm happy with that.

**Comment by hellogerard** [comment]
I think I'll make it a config, to include it or not, and upgrade the version.

**Comment by dubvfan87** [comment]
That sounds like a good plan! Thanks.
