### ISSUE TITLE
TypeError: Object [object Object] has no method 'where'

### ISSUE THREAD

**Issue by sbernheim4** [Differential/meteor-blog#191]
I'm trying to create a basic blog page on a website I'm working on. When I added this package I go the following error:

W20150628-20:32:25.802(-4)? (STDERR)          
W20150628-20:32:25.804(-4)? (STDERR) /Users/samuelbernheim/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150628-20:32:25.804(-4)? (STDERR) 						throw(ex);
W20150628-20:32:25.804(-4)? (STDERR) 						      ^
W20150628-20:32:25.805(-4)? (STDERR) TypeError: Object [object Object] has no method 'where'
W20150628-20:32:25.805(-4)? (STDERR)     at __coffeescriptShare (packages/davidsichau:blog/server/boot.coffee:34:11)
W20150628-20:32:25.805(-4)? (STDERR)     at /Users/samuelbernheim/Desktop/JBS_2015/CS152/Kinetic/.meteor/local/build/programs/server/boot.js:229:5

I checked the lines of the file it referenced and couldn't even find any reference to something called where. Is there something (a package) I am missing. 

These are the other packages I'm using:  
accounts-password            1.1.1  Password support for accounts
alanning:roles               1.2.13  Role-based authorization
davidsichau:blog             0.7.4  A package that provides a blog at /blog
ian:accounts-ui-bootstrap-3  1.2.67  Bootstrap-styled accounts-ui with multi-language support.
insecure                     1.0.3  Allow all database writes by default
iron:router                  1.0.9  Routing specifically designed for Meteor
meteor-platform              1.2.2  Include a standard set of Meteor packages in your app
twbs:bootstrap               3.3.5  The most popular front-end framework for developing responsive, mobile first projects on the web.

**Comment by hellogerard** [comment]
It does reference `boot.coffee:34`, which is this line:

```
if Post.where({ excerpt: { $exists: 0 }}).length
```

Do you have another collection variable or class named `Post` by any chance? Might be conflicting. These need to be prefixed or namespaced (see #82).
