### ISSUE TITLE
Use featured image for social sharing thumbnail if there is one

### ISSUE THREAD

**Issue by abhirakshit** [Differential/meteor-blog#192]
Hey guys,

The blog does a fine job for setting the og:title and og:description but for some reason the og:image remains empty. I am uploading the images using the built in upload system and not using aws.

Is there something which is needed to be done explicitly to get it working or is the feature not implemented yet?

**Comment by hellogerard** [comment]
It is working for me. Right now, the logic is that the first image in the blog post body is used as a thumbnail. The featured image is _not_ used as a social sharing thumbnail, although we could make that change. Do you have images in your blog post body?

**Comment by abhirakshit** [comment]
No I don't have images in my blog body just the featured image which shows on top above the blog heading. 
So you mean if I put any images in the actual blog body they will work for social sharing but not the hero image. Is that correct?

**Comment by hellogerard** [comment]
That's correct.

**Comment by abhirakshit** [comment]
Can I expect a feature to be able to use the hero image as the social image anytime soon?

**Comment by abhirakshit** [comment]
Thanks for accepting as a TODO.
