### ISSUE TITLE
I can't install this blog? error logs

### ISSUE THREAD

**Issue by leungcheukfai** [Differential/meteor-blog#196]
I just tried to test this out, but I ran into the below problems, not sure how to resolve this.    

While building the application:
   client/compatibility/bower_components/jquery-sortable/source/example.html:1:
   bad formatting in HTML template
   client/compatibility/bower_components/medium-editor/src/wrappers/end.js:2:5:
   Unexpected token )

   client/compatibility/bower_components/medium-editor/src/wrappers/start.js:16:3:
   Unexpected end of input
   client/compatibility/bower_components/blueimp-tmpl/js/compile.js:1:15:
   Unexpected token ILLEGAL
   client/compatibility/bower_components/jquery/src/intro.js:46:3: Unexpected
   end of input
   client/compatibility/bower_components/jquery/src/outro.js:1:17: Unexpected
   token )

   client/compatibility/bower_components/jquery-sortable/source/css/bootstrap-switch.css:
   missing '{' near line 2:1
   client/compatibility/bower_components/jquery-sortable/source/css/vendor.css:
   missing '{' near line 3:1

**Comment by hellogerard** [comment]
Can't replicate this. Are you on Windows by any chance?

**Comment by leungcheukfai** [comment]
I am using mac with terminal

**Comment by hellogerard** [comment]
@leungcheukfai Are you on 1.2? Can you clone this repo and try it again on `master`?
