### ISSUE TITLE
Medium features worth doing

### ISSUE THREAD

**Issue by ryw** [Differential/meteor-blog#2]
Example page: https://medium.com/tech-blogging/3bbbb45587d6

* Full width header image
* Title block that parallaxes and fades as you scroll into the article
* Per-paragraph comments

Question is if this should be built into meteor-blog, or just our implementations? If we want to implement a feature on all our blogs, I'd say we just build it into meteor-blog.

**Comment by dandv** [comment]
> Can you create separate issues for these?

Would love to see separate issues for @ryw's feature suggestions as well, so we could close this meta-issue.

**Comment by MarcioAntonioRezende** [comment]
When i look to enter a image, it add a icon for file missing...
