### ISSUE TITLE
where to add the ui for user to login

### ISSUE THREAD

**Issue by balasivagnanam** [Differential/meteor-blog#201]
Thanks for this awesome project, 
Currently I am doing a static website in which I am trying to integrate a blog. But problem is I dont have any login for both blog and the website.
So when I add the package and go the pages its empty and says "This blog is looking pretty empty..." even after adding accounts-ui I am not getting a login button here.

lets say If I want to have a valid user I need to add accounts-ui and bring the user to that page before landing to blog page ? I dont want to have a login button to my website.

If I have to add a login, then where do I do this ?

**Comment by hellogerard** [comment]
The blog package doesn't know or care anything about how you authenticate. I'm afraid you are on your own to figure out where/when/how to allow your users to log in.  You could use `accounts-ui`, or `useraccounts:core`, or any of the few other authentication UI packages on Atmosphere. 

It sounds you want to have a standalone login page. If so, I recommend [`useraccounts-core`](https://atmospherejs.com/useraccounts/core). It's the most popular right now, I believe.

**Comment by balasivagnanam** [comment]
do u think i should have a route to blog that where i can authenticate and can route to /blog after that ?

**Comment by balasivagnanam** [comment]
anyways thanks.. let me try it///
