### ISSUE TITLE
Medium style editor does't apply the selected text style

### ISSUE THREAD

**Issue by roberto-delfiore** [Differential/meteor-blog#204]
Editing a post, if I select a text to apply a style, the style bar appear but It does not seem to work: any button has no effect on the text style. The bar disappear with no post changes.

I'm using Meteor 1.1.0.3 with the following packages:
accounts-password  1.1.1  Password support for accounts
accounts-ui        1.1.5  Simple templates to add login widgets to an app
iron:router        1.0.9  Routing specifically designed for Meteor
meteor-platform    1.2.2  Include a standard set of Meteor packages in your app
mrt:bootstrap-3    0.3.8  Provides bootstrap 3.
ryw:blog           0.7.1  A package that provides a blog at /blog

How can I fix it?

Thank you in advance

**Comment by hellogerard** [comment]
It's working for me with the latest versions of all those packages. Are all those the latest?

What browser/OS are you using?

**Comment by roberto-delfiore** [comment]
I'm using OSX Yosemite 10.10.3 and now I tested with Safari, Chrome and Firefox: the problem is only with Safari. I'm using the version 8.0.6.

Thank you and congratulation for this project.

**Comment by Danappelxx** [comment]
:+1: this happens to me as well. Quite frustrating that it works on Chrome but not on Safari.

**Comment by hellogerard** [comment]
Looks like an issue with Medium Editor (https://github.com/yabwe/medium-editor/issues/507). Upgrading the version should fix this.
