### ISSUE TITLE
Meteor 1.2 compatibility

### ISSUE THREAD

**Issue by hellogerard** [Differential/meteor-blog#209]
Make compatible with Meteor 1.2. Will break backwards-compatibility.

https://quip.com/RXFlAk9Rc2xI

**Comment by hellogerard** [comment]
Closed by 2ec3cb1.

**Comment by nirmalr** [comment]
I still get the following error on install:

Changes to your project's package version selections:

ryw:blog  added, version 0.5.1

ryw:blog: INCOMPATIBLE WITH METEOR 0.9.0 OR LATER

Should I ignore it and assume it will work based on the fact it was addressed back in Oct 2015?

Please suggest
