### ISSUE TITLE
how to comment?

### ISSUE THREAD

**Issue by zhaoyao91** [Differential/meteor-blog#210]
Is there a way to let users of the meteor app make comments on the posts?
It seems that meteor-blog doesn't support traditional comments on the bottom of the posts.
I don't know how to use the so-called sideComments system. I have config it as the doc says, 

      comments: {
        useSideComments: true,
        allowAnonymous: true
    }

but I don't see any different in my test project.
thanks for any help

**Comment by hellogerard** [comment]
No, there is no way to allow traditional comments on the bottom of the posts.

There is support for Disqus commenting a the bottom of the posts.

The Side Comments simply pulls in http://aroc.github.io/side-comments-demo/. It should function like that. Are there errors in the browser or server console?  I haven't looked that that in quite some time and it doesn't seem to get much use.

**Comment by zhaoyao91** [comment]
@hellogerard thanks. In fact side comment is not the first choice for our app, we prefer more a traditional bottom comment system.If it's clear that it doesn't support it, I'll take some time to think how to extend it. I also appreciate any suggestion for this. thanks
