### ISSUE TITLE
Meteor 1.2 less constraints and compatibility

### ISSUE THREAD

**Issue by Neruell** [Differential/meteor-blog#212]
If i manually update the package to ryw:blog@0.7.1 I get the following message.

Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.0_3.
Constraints on package "less":
* less@=2.5.0_3 <- top level
* less@2.5.0_1 <- accounts-ui 1.1.6
* less@2.5.0_1 <- accounts-ui-unstyled 1.1.8 <- accounts-ui 1.1.6
* less@1.0.5 <- ryw:blog 0.7.1
* less@1.0.11 <- lovetostrike:shareit 0.4.1 <- ryw:blog 0.7.1
* less@2.5.0_1 <- gfk:notifications 1.1.4 <- ryw:blog 0.7.1

If I just run meteor add ryw:blog I get the 0.5 version which is not compatible to the latest versions.

I assume that this line needs updating
Package.onUse(function(api) { 
      'less@2.5.0_3',  
], 'client');  

instead of just
         'less',


**Comment by hellogerard** [comment]
Just got this package 1.2 compatible yesterday. But it's in master and not released yet (forthcoming).  If you're really impatient, you can install this repo in your app locally. 

Also, it's weird that you would get 0.5 by default. That's very old.
