### ISSUE TITLE
Adding the blog to my project breaks all other routes.

### ISSUE THREAD

**Issue by ggndpsingh** [Differential/meteor-blog#218]
I've been waiting for an update for this package for a few days and today I finally saw it and installed it. I was very happy that it worked with the latest release of meteor. But after playing around with it for a while when I tried to look at the rest of my app, all I got was 'There is no route defined for the url'.

Any ideas how I can fix this?

**Comment by hellogerard** [comment]
Hey, yeah, the hardest part of this release was getting it to work with
both routers. It works on my test app. What is your config? Can you put a
small repo on github that reproduces the issue?
On Sun, Oct 11, 2015 at 7:11 AM ggndpsingh <notifications@github.com> wrote:

> I've been waiting for an update for this package for a few days and today
> I finally saw it and installed it. I was very happy that it worked with the
> latest release of meteor. But after playing around with it for a while when
> I tried to look at the rest of my app, all I got was 'There is no route
> defined for the url'.
>
> Any ideas how I can fix this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Differential/meteor-blog/issues/218>.
>
-- 
Gerard Sychay | Partner at Differential | @hellogerard | 859-802-5513

**Comment by purplecones** [comment]
I too am having this issue, however in a somewhat opposite way. I have an app using Flow Router and when I added this package, all of my original routes still work except that the new blog path does not. My config file right now is: 
```
Blog.config({
  basePath: '/blog',
  adminBasePath: '/blogAdmin',
	adminRole: 'admin',
	authorRole: 'blogAuthor'
});
``` 
and I get this error in browser console ```There is no route for the path: /blog```

I also started seeing this in the server console ```I20151012-10:07:31.487(-4)? Meteor._wrapAsync has been renamed to Meteor.wrapAsync```

**Comment by hellogerard** [comment]
@purplecones I'm afraid I can't reproduce yours either. Can you take your app, and start removing things until you get a small repo that contains the error? It's the best way to figure this out. There are just many variables here (your other app routes, other app packages)

**Comment by purplecones** [comment]
ok, if I start fresh with ```meteor create blog``` and have the following code: https://gist.github.com/purplecones/6736e75655ee2cbad44d

packages:
```
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifiers      # JS/CSS minifiers run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

ryw:blog
kadira:flow-router
accounts-password
accounts-ui
alanning:roles
```

blog.html:
```
<head>
  <title>blog</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>

  {{> hello}}

  {{> loginButtons }}
</body>

<template name="hello">
  <button>Click Me</button>
  <p>You've pressed the button {{counter}} times.</p>
</template>
```

blog.js:
```
Blog.config({
  basePath: '/blog',
  adminBasePath: '/blogAdmin',
	adminRole: 'admin',
	authorRole: 'blogAuthor'
});

if (Meteor.isClient) {
  Accounts.ui.config({
    passwordSignupFields: 'USERNAME_ONLY'
  });
  // counter starts at 0
  Session.setDefault('counter', 0);

  Template.hello.helpers({
    counter: function () {
      return Session.get('counter');
    }
  });

  Template.hello.events({
    'click button': function () {
      // increment the counter when button is clicked
      Session.set('counter', Session.get('counter') + 1);
    }
  });
}

if (Meteor.isServer) {
  Meteor.startup(function () {
    if (Meteor.users.find().count() === 0) {
    	let userId;
    	userId = Accounts.createUser({
    		email: 'admin@test.com',
    		username: 'admin',
    		password: 'admin',
    		profile: {
    			firstName: 'ADMIN',
    			lastName: 'ADMIN'
    		}
    	});
    	Roles.addUsersToRoles(userId, ['admin'], Roles.GLOBAL_GROUP);
    }
  });
}
```

The route /blog still shows the default counter screen.

**Comment by hellogerard** [comment]
Ah, thanks for the gist. The problem was that the app is missing `kadira:blaze-layout`. If I run `meteor add kadira:blaze-layout`, it works (you will see the "This blog is looking pretty empty..." message).

Does that fix your app?

I guess my assumption was that if you use Flow Router, you will use Blaze Layout (meteor-blog doesn't support React right now). Not sure what to do if anything. I think I did try rendering everything on my own using Blaze, but it would have been just rewriting Blaze Layout.

**Comment by ggndpsingh** [comment]
I figured out my problem. Couldn't give it any time yesterday. My problem was fairly simple. After adding the blog package, there were two templates named "notifications" and that caused all the problems.

I guess a lot of people will have a notifications template in their apps and they'll have to deal with the same problem. Perhaps, you should change the name of the blog's template to something like "blogNotifications" in order to avoid this issue.

**Comment by purplecones** [comment]
@hellogerard 
Thanks, it did fix the issue. I also had to add packages ```check``` and ```random``` for it to work.

**Comment by hellogerard** [comment]
@purplecones Great! I also saw the `check` package warning and added it. I removed the need for the `random` package. 

@ggndpsingh That `notifications` template came from a meteor package dependency. I replaced it with a simpler Toast-like package. It is more or less a jquery plugin and conatins no meteor templates.

**Comment by 1thrasher** [comment]
I'm still having issues with the blog routes not working properly using iron-router.

I'm using the same gist as @purplecones above (without `kadira:flow-router`, adding `iron:router`, `check`, and `random` packages).

If I add a link to the main blog.html template `<br/><a href="{{pathFor 'blogIndex'}}">Blog</a>`  and console.log yields: `pathFor couldn't find a route named "blogIndex"`

If I navigate to http://localhost:3000/blog then there's no error. 

Also, if I create and publish a post, then extend to use a custom index template:
```
if (Meteor.isClient) {
   Blog.config({
       blogIndexTemplate: 'myBlogIndexTemplate'
     });
   ...
```
No posts display in the new template. (I assume these are separate issues, but thought I'd mention it.)

**Comment by hellogerard** [comment]
@1thrasher You can't use `{{pathFor 'blogIndex'}}` because Iron Router does not know about the blog routes. It's not documented, but you should be able to use `{{blogPathFor 'blogIndex'}}` instead, which is what is used internally, but I haven't tried it. If it works, I'll add it to the documentation.

Your custom template (`myBlogIndexTemplate`) needs to use the package inclusion helpers (`{{> blogIndex}}`). Do you have that?

**Comment by 1thrasher** [comment]
@hellogerard the `{{blogPathFor 'blogIndex'}}` helper worked, thanks! (However, do note `{{pathFor 'blogIndex'}}` worked on blog v0.7.1.

As for the helper, I'm using the custom template as mentioned in the docs as follows:
```
<template name="myBlogIndexTemplate">
  <h1>Welcome to my Blog</h1>
  <ul>
    {{#each posts}}
      <li>
        <h2>{{title}}</h2>
        <p>Published on {{publishedAt}}</p>
        <p>Excerpt: {{excerpt}}</p>
      </li>
    {{/each}}
  </ul>
</template>
```

**Comment by hellogerard** [comment]
Ah, see #219.  Please give ideas if you have them. I'm afraid that will have to come out.
