### ISSUE TITLE
I can't use custom templates

### ISSUE THREAD

**Issue by cesarve77** [Differential/meteor-blog#222]
Hi first thanks for this great blog.

But Im not sure how use custom templates.

I can config my custom template and see my html but I can access the data.
For example subsReady or posts variables are undefined.

Thanks for help

**Comment by hellogerard** [comment]
It's working for me. Can you post some code? Like your custom template and Blog config? BTW, the variable is `blogReady`, not `subsReady`. If you are using `subsReady`, you will not see anything.

**Comment by cesarve77** [comment]
Ready! I'm really sorry.

I just re install from git and ready. I don't know why, but was using a old version from blog,

thanks and sorry

**Comment by hellogerard** [comment]
NP!
