### ISSUE TITLE
Suggested way to handle non-blog 404

### ISSUE THREAD

**Issue by Christilut** [Differential/meteor-blog#223]
I usually use this route to catch 404s:
```javascript
Router.route("/(.*)", {
    name: "notFound",
    action: function () {
        this.render('pageNotFound')
        this.next()
    }
})
````
but with the blog package installed /blog is seen as a 404. Whats the suggested way to handle bad links that are not in the blog?

Without the above route:
The missing blog links do get a proper 404, e.g.: /blog/doesnt-exist gets the proper 404 page but /something-else does not.

**Comment by hellogerard** [comment]
@Christilut Just pushed a commit that takes care of this, I believe. Can you clone this repo, and try the latest `master` in your app?  Let me know if you need help with that, and let me know how it goes.

**Comment by Christilut** [comment]
Thanks, this works great.

(Had to remove this.next() from my own code above, if anyone ever uses that)
