### ISSUE TITLE
Uncaught Error: No such function: session

### ISSUE THREAD

**Issue by kyv** [Differential/meteor-blog#233]
meteor add ryw:blog

   create new blog post

  click link to new blog post

result:  blank page and the following error in the consol. 

Uncaught Error: No such function: session(anonymous function) @ blaze.js:3149

Spacebars.call @ spacebars.js:167Spacebars.mustacheImpl @ spacebars.js:104Spacebars.dataMustache @ spacebars.js:136(anonymous function) @ template.blog.js:101(anonymous function) @ blaze.js:2674(anonymous function) @ blaze.js:1872Template._withTemplateInstanceFunc @ blaze.js:3671(anonymous function) @ blaze.js:1870Blaze._withCurrentView @ blaze.js:2211viewAutorun @ blaze.js:1869Tracker.Computation._compute @ tracker.js:349Tracker.Computation @ tracker.js:237Tracker.autorun @ tracker.js:588Blaze.View.autorun @ blaze.js:1882(anonymous function) @ blaze.js:2673fireCallbacks @ blaze.js:1952Tracker.nonreactive @ tracker.js:615(anonymous function) @ blaze.js:1949Blaze._withCurrentView @ blaze.js:2211Blaze._fireCallbacks @ blaze.js:1948Blaze._createView @ blaze.js:1966Blaze._materializeView @ blaze.js:2011materializeDOMInner @ blaze.js:1473Blaze._materializeDOM @ blaze.js:1415Blaze._materializeDOM @ blaze.js:1424(anonymous function) @ blaze.js:2053Tracker.nonreactive @ tracker.js:615Blaze._materializeView @ blaze.js:2017Blaze.render @ blaze.js:2310DynamicTemplate.insert @ iron_dynamic-template.js:516Router.insert @ iron_router.js:1636maybeAutoInsertRouter @ iron_router.js:1626

**Comment by kyv** [comment]
Okay sorry this was my bad. I would delete it but I don´t see a delete button.

**Comment by rmuratov** [comment]
So what was the issue?
