### ISSUE TITLE
Best way to listen for new blog posts ?

### ISSUE THREAD

**Issue by devfordays** [Differential/meteor-blog#266]
Greetings, 

I am trying to find a way to listen for new blog posts. One logical solution I tried would be to use the meteor collection hooks https://github.com/matb33/meteor-collection-hooks  package. After digging through the post.coffee file I learned to reference the blog posts collection like Blog.Post._collection  ... but Blog.Post._collection.after and Blog.Post._collection._collection both return undefined which is the syntax needed in order to run the collection hooks code which can be found below.  Any ideas on how I can set up up a listener after a blog post is published? Would like to email notify my blog subscribers when a new post is put up!

Here is some sample code ... which I run server side of course.

```
Blog.Post._collection.after.insert(function(userId, doc){
  console.log(`hey blog post was just inserted`);
});
```

**Comment by hellogerard** [comment]
I'm not sure why it can't see the collection. Might have something to do with package visibility. Meteor Blog uses Minimongoid for its database abstraction. Using its 'after' hooks to do this worked for me:

``` javascript
Blog.Post.after_save = function(userId, doc){
  console.log(`hey blog post was just inserted`);
};
```

Documentation is light, but the Minimongoid code is really easy to understand: https://github.com/Exygy/minimongoid/blob/master/lib/minimongoid.coffee#L313-L316

**Comment by devfordays** [comment]
Thanks for the tip. You sir are a lifesaver.
