### ISSUE TITLE
Question: can this package work with react-router ?

### ISSUE THREAD

**Issue by edavidzeron** [Differential/meteor-blog#281]
I'm just curious if its compatible ...

**Comment by hellogerard** [comment]
Nope, I'm afraid not. The first step would be to port all the Blaze templates over to React...

**Comment by octohedron** [comment]
I was wondering the same thing, Is it possible to run both at the same time? As in, render react stuff in one part of the screen and the blog stuff in another or in different routes?

**Comment by hellogerard** [comment]
You can render React components within your custom Blaze template with something like https://atmospherejs.com/gadicc/blaze-react-component. But as far as routing, I don't think there's a quick solution.
